[package]
name = "rust-wasm"
authors = ["Luz"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.91"
web-sys = { version = "0.3", features = [ "Window", "Document", "HtmlElement" ] }


[profile.release]
opt-level = "s"
